apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openlineage-fluentd.fullname" . }}
  labels:
    {{- include "openlineage-fluentd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openlineage-fluentd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openlineage-fluentd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openlineage-fluentd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/entrypoint.sh
            - -p
            - /fluentd/openlineage-parser
          env:
            - name: MARQUEZ_HTTP_ENDPOINT
              value: {{ include "openlineage-fluentd.marquez-url" . | quote}}
          ports:
            - name: http
              containerPort: 9880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 24220
          readinessProbe:
            httpGet:
              path: /
              port: 24220
          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              name: fluent-conf
              subPath: fluent.conf  
            - mountPath: /fluentd/openlineage-parser/parser_openlineage.rb
              name: fluent-plugin
              subPath: parser_openlineage.rb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fluent-conf
          configMap:
            name: fluent-conf
        - name: fluent-plugin
          configMap:
            name: fluent-plugin
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
