apiVersion: v1
data:
  fluent.conf: |-
    <source>
      @type http
      port 9880
      <parse>
        @type openlineage
      </parse>
    </source>

    # metrics for liveness and readiness probes
    <source>
      @type monitor_agent
      bind 0.0.0.0
      port 24220
    </source>


    # https://docs.fluentd.org/output/http
    <match api.v1.lineage> # tag should match fluentd input endpoint url http://localhost:9880/api/v1/lineage
      @type copy
      <store>
        @type http
        endpoint_url "#{ENV['MARQUEZ_HTTP_ENDPOINT']}"
        content_type application/json
        bulk_request false # available since using https://github.com/fluent-plugins-nursery/fluent-plugin-out-http
        buffered true
        serializer json
        retryable_response_codes 408, 429, 500, 502, 503

        <buffer>
          @type file
          path /tmp/openlineage/buf/chunk-*
          flush_mode immediate
        </buffer>
      </store>

      <store>
        @type stdout # testing purpose to demonstrate that copy is working
      </store>

      # other output stores can be put

    </match>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluent-conf
